version: '3.8'

services:

  server:
    build: ./server
    image: server
    ports:
      - 5000:5000
    restart: always
    logging:
      driver: "json-file"

  client:
    build: ./client
    image: client
    ports:
      - 3000:3000
    depends_on:
      - server
    restart: always
    logging:
      driver: "json-file"

  # proxy:
  #   image: nginx:mainline
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 443:443
  #     - 80:80



# version: '3.8'

# services:

#   server:
#     image: server
#     build: 
#       context: .
#       dockerfile: server/Dockerfile
#     restart: always
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "3"


#   client:
#     image: client
#     build: 
#       context: ./client
#       dockerfile: Dockerfile
#     depends_on:
#       - server
#     restart: always
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "3"
