version: '3.8'

services:
    server:
        build: ./server
        image: server
        ports:
            - 5000:5000
        restart: always
        logging:
            driver: 'json-file'

    client:
        build: ./client
        image: client
        volumes:
            - ./ssl:/etc/ssl/certs/
        ports:
            - 3000:3000
        depends_on:
            - server
        restart: always
        logging:
            driver: 'json-file'

    proxy:
        image: nginx:mainline
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 443:443
            - 80:80
