version: '3.8'

services:
    server:
        build: ./server
        image: server
        ports:
            - 127.0.0.1:5000:5000
        environment:
            - LOG_DIR=/app/logs
        volumes:
            - /var/log/nikassdgym:/app/logs
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '5'

    client:
        build: ./client
        image: client
        ports:
            - 127.0.0.1:3000:3000
        depends_on:
            - server
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '5'